FROM python:3.12-slim

WORKDIR /app

COPY Backend/requirements_backend.txt ./
RUN pip install --no-cache-dir -r requirements_backend.txt

COPY Backend/ ./
COPY ML/ ./ML/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
